### ISSUE TITLE
PCC top_cor and base_cor

### ISSUE THREAD

**Issue by mndstrmr** [microsoft/cheriot-ibex#9]
Currently the PCC is stored as a `pcc_cap_t` in the CSR block. This means it does not have cached top_cor and base_cor. When the PCC is converted to a `full_cap_t`, instead of computing `top_cor` and `base_cor` the `pcc2fullcap` function currently just sets them both to zero.

Forgive me if I am wrong, but that seems like it cannot be right.

Since the PCC address is not stored anywhere (note that this is not the same as PC), the `top_cor` and `base_cor` fields (as well as `top33` and `base32`) must instead be stored with the PCC. The stored PCC could therefore be a `full_cap_t` and `pcc_cap_t` could be removed from CherIoT-ibex altogether.

**Comment by davidchisnall** [comment]
> Since the PCC address is not stored anywhere (note that this is not the same as PC)

Can you clarify that?  This has traditionally been true on all CHERI systems and I'm not sure how we changed that.

**Comment by kliuMsft** [comment]
@mndstrmr You are absolutely right that top_cor/base_cor == 0 can't be right all the time. However in this case (pcc_full_cap), top_cor and base_cor are actually never used (since we really only need the expanded top/base and exp to convert between pcc and reg_cap). 

The reason I still want a separate structure type for pcc_cap is really try to save a few flops (which may not work out too well) and not having to worry about keeping the cor values consistent all the time. The conversion to/from full_cap is still causing too much confusion though, so likely going to have to clean it up further.

**Comment by mndstrmr** [comment]
Ah, you are totally right - I should have spotted that. Turns out a check we had in place was a bit too strong. Relaxing it works and everything still proves.

Thanks!
